
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 885460
	#The name of the modpack
	modpackName = "All of Create"
	#The version of the modpack
	modpackVersion = "v3.7"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

